sudo: required
language: python
services:
  - docker

before_install:
  - sudo apt-get -qq update
  - npm install -g npm@'==4.6.0

install:
  - pip install -r requirements.txt

script:
  - find . -name "*.yml" | xargs yamllint
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
