---

- name: install utils
  package:
    name: "{{ item }}"
    update_cache: true
    state: present
  register: network_access
  until: network_access is success
  retries: 10
  delay: 2
  with_items: "{{ base_utils }}"
