---
# Standards: 0.2
dependency:
  name: galaxy
  requirements_file: requirements.yml
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: base-utils-centos
    image: milcom/centos7-systemd
    privileged: true
  - name: base-utils-ubuntu
    image: ubuntu
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
  playbooks:
    converge: playbook.yml
  lint:
    name: ansible-lint
